#! /bin/sh

# desktop config

bspc monitor DP-0 -d I II III IV V VI VII VIII IX X
bspc monitor %USB-C-0.2 -d 1 2 3 4 5 6 7 8 9 0

bspc config -m DP-0 bottom_padding 80
bspc config -m %USB-C-0.2 top_padding 40

bspc config -m DP-0 top_padding 40

# borders and gaps

bspc config border_width         0
bspc config window_gap           20
bspc config active_border_color "#0066cc"
bspc config focused_border_color "#0066cc"

# layout stuff

bspc config split_ratio          0.48
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# mouse pointer stuff

bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# window rules
bspc rule -a lattedock center=false

# other shit

xrdb ~/.Xresources > /dev/null
exec ~/.config/autostart.sh

