#!/bin/sh

alias ls='lsd'
alias ll='lsd -la'
alias lh='lsd -d .*'
alias clr='clear'
alias root='sudo su -'
alias mkdir='mkdir -pv'
alias fetch='neofetch'
alias rm='rm -I --preserve-root'
alias cp='cp -i'
alias own='chmod +x'
alias rs='source ~/.zshrc'
alias javas='archlinux-java'
alias home='cd ~'
alias grep='grep --color'
alias findline='grep -rnw'
alias fln='grep -rnw'
alias top='bpytop'
alias math='bc -l'
alias music='~/scripts/music.sh'
alias gtop='nvidia-smi'
alias usage='du -h --max-depth=1 | sort -hr'   
alias sendkey='DISPLAY=:0 xdotool key'
alias sendtype='DISPLAY=:0 xdotool type --delay 100'
alias sendbacks='sendkey --repeat 10 BackSpace'
alias laptop='ssh 10.0.1.22'
alias pi='ssh 10.0.1.2'
alias sudo='sudo -p "Enter user password:"'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias svim='sudo nvim'
alias svi='sudo nvim'
alias pacman='sudo pacman'
alias tls='tmux ls'
alias ta='tmux attach -t'
alias tn='tmux new -s'
alias unlck='~/scripts/unlock'
alias lock='~/scripts/lock'
alias plss='pstree -TSlhC age'
alias pls='plss -p'
alias tk='tmux kill-session -t'
alias kernels='ls /boot | grep vmlinuz'
alias trname='tmux rename-session -t'
alias doom='~/.emacs.d/bin/doom'
alias hostname='cat /etc/hostname'
alias pasteIX='curl -F "f:1=<-" ix.io'
alias move="mv"
alias copy="cp"
alias testInternet="ping 8.8.8.8"
alias rst="home && c"
alias u='clear && ufetch | lolcat'
