#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# desktop config

bspc monitor DP-0 -d I II III IV 
bspc monitor HDMI-0 -d V VI VII VIII IX X

# borders and gaps

bspc config border_width         0
bspc config window_gap           20
bspc config active_border_color "#0066cc"
bspc config focused_border_color "#0066cc"

# layout stuff

bspc config split_ratio          0.48
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# mouse pointer stuff

bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# other shit

xrdb ~/.Xresources > /dev/null
~/.config/autostart.sh > /dev/null

